<?php

/**
 * @file
 * Conditional logic and data processing for the UIkit theme.
 */

use Drupal\uikit\UIkit;

/**
 * Load UIkit's include files for theme processing.
 */
UIkit::loadIncludeFile('inc', 'uikit', 'theme', 'preprocess', 'includes');
UIkit::loadIncludeFile('inc', 'uikit', 'theme', 'process', 'includes');
UIkit::loadIncludeFile('inc', 'uikit', 'theme', 'theme', 'includes');
UIkit::loadIncludeFile('inc', 'uikit', 'theme', 'alter', 'includes');
